FROM elixir:1.13 AS builder

# The following are build arguments used to change variable parts of the image.
# The name of your application/release (required)
ARG APP_NAME
ARG SECRET_KEY_BASE

# ENV APP_NAME=${APP_NAME}
ENV APP_NAME=live_k8s
ENV SECRET_KEY_BASE=${SECRET_KEY_BASE}

# set build ENV
ENV MIX_ENV=prod

# By convention, /opt is typically used for applications
WORKDIR /opt/app

# This step installs all the build tools we'll need
RUN apt-get update && \
  apt-get install -y \
    git \
    nodejs \
    npm && \
  mix local.rebar --force && \
  mix local.hex --force

# This copies our app source code into the build container
COPY . .

# Run the build
RUN mix do deps.get, deps.compile, clean, compile

# Run the release
WORKDIR /opt/app
RUN \
  mkdir -p /opt/built && \
  mix release && \
  mv _build/prod/rel/live_k8s/* /opt/built

#
# Production docker image
#

# From this line onwards, we're in a new image, which will be the image used in production
FROM elixir:1.13

# The name of your application/release
ARG APP_NAME

# Set the workdir and copy the released app from the builder container into the production container.
WORKDIR /opt/live_k8s
COPY --from=builder /opt/built .

# Copy the docker entrypoint which is not part of the app release into the production container.
COPY --from=builder /opt/app/entrypoint.sh .
RUN chmod +x ./entrypoint.sh

RUN echo $(ls)
# We need to set these environment variables because the entrypoint script uses them.
ENV APP_NAME=live_k8s

# Launch the app
ENTRYPOINT ["./entrypoint.sh"]
