version: '3'
services:
  live_k8s:
    image: test
    network_mode: "host"
    build:
      context: .
      dockerfile: ./Dockerfile

    # ports:
    #   - 4000:4000
    volumes:
      - /var/log/live_k8s:/var/log