apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-k8s
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: live-k8s

  template:
    metadata:
      labels:
        app: live-k8s
    spec:
      containers:
      - name: phoenix-live-k8s
        image: test3:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        - name: ERL_DIST_PORT
          value: "8001"
        - name: RELEASE_COOKIE
          value: secret-cookie
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
---
# load balancer to expose the app
kind: Service
apiVersion: v1

metadata:
  name: live-k8s-lb
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: live-k8s
  ports:
    - name: http
      port: 8000
      targetPort: 4000
---
# headless service needed for libcluster
kind: Service
apiVersion: v1

metadata:
  name: live-k8s-nodes
  namespace: default
spec:
  clusterIP: None
  selector:
    app: live-k8s
  ports:
    - name: epmd
      port: 4369